### ISSUE TITLE
converting from .tga to .pct_mip failing

### ISSUE THREAD

**Issue by Kfestofil** [vash2pid/texmipper#1]
So I am using IndexV2 to export the textures into .tga and then trying to use the tool on them (not even changing them, just using the freshly exported files) but it crashes and i can't figure out why, the v1.0 also does this

Terminal output:
---

Processing file 1 of 1
Texture file selected:
D:\modding garbage\ts_game_logo_part_sm.tga
D:\modding garbage\resources.pak

resrouce.pak file found:
D:\modding garbage\resources.pak
.resource not found in pct folder, checking texture folder.

.resource file found textures/ui/title_screen/ts_game_logo_part_sm.asset/ts_game_logo_part_sm.pct.resource

Converting from *.tga to *.pct_mip files based on the number of mipmaps in resource file

Converting ts_game_logo_part_sm_0.pct_mip
System.ArgumentException: Value does not fall within the expected range.
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHR(Int32 errorCode)
   at DirectXTexNet.ScratchImageImpl.Compress(DXGI_FORMAT format, TEX_COMPRESS_FLAGS compress, Single threshold)
   at texmipper.TexMipper.ConvertToPCT(ResourcePct resourcePCT, String inputtexturefilepath) in D:\dev\SM2\texmipper\TexMipper.cs:line 177
   at texmipper.TexMipper.Main(String[] args) in D:\dev\SM2\texmipper\TexMipper.cs:line 71

Press any key to close this window...
---

**Comment by Kfestofil** [comment]
So well... I asked about this on the DirectXTexNet github and I got information that the Compress() method takes in the Compressed BC format, and the code is passing the B8G8R8A8_UNORM format which is apparently wrong. I am trying to convert the ts_game_logo_part_sm texture .tga file into a .pct_mip.
What should the code do in this case then??

**Comment by Kfestofil** [comment]
Ok What needs to be done is basically changing the line there and literally put in Convert() instead of Compress()
